using CluedIn.Core.Data;
using CluedIn.Core.Data.Vocabularies;

namespace CluedIn.Vocabularies.CommonDataModel.ApplicationCommon
{
    public class CurrencyVocabulary : SimpleVocabulary
    {
        public CurrencyVocabulary()
        {
            VocabularyName = "Currency";
            KeyPrefix = "commonDataModel.currency.applicationcommon";
            KeySeparator = ".";
            Grouping = CommonDataModelEntityTypes.Currency;

            AddGroup("Currency Details for ApplicationCommon", group =>
            {
			    StatusCode = group.Add(new VocabularyKey(nameof(StatusCode), "Status Reason", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    ModifiedOn = group.Add(new VocabularyKey(nameof(ModifiedOn), "Modified On", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    StateCode = group.Add(new VocabularyKey(nameof(StateCode), "Status", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    VersionNumber = group.Add(new VocabularyKey(nameof(VersionNumber), "Version Number", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    ImportSequenceNumber = group.Add(new VocabularyKey(nameof(ImportSequenceNumber), "Import Sequence Number", VocabularyKeyDataType.Integer, VocabularyKeyVisibility.Visible)); 
			    OverriddenCreatedOn = group.Add(new VocabularyKey(nameof(OverriddenCreatedOn), "Record Created On", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    CreatedOn = group.Add(new VocabularyKey(nameof(CreatedOn), "Created On", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    TransactionCurrencyId = group.Add(new VocabularyKey(nameof(TransactionCurrencyId), "Transaction Currency", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    ExchangeRate = group.Add(new VocabularyKey(nameof(ExchangeRate), "Exchange Rate", VocabularyKeyDataType.Number, VocabularyKeyVisibility.Visible)); 
			    CurrencySymbol = group.Add(new VocabularyKey(nameof(CurrencySymbol), "Currency Symbol", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    CurrencyName = group.Add(new VocabularyKey(nameof(CurrencyName), "Currency Name", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    ISOCurrencyCode = group.Add(new VocabularyKey(nameof(ISOCurrencyCode), "Currency Code", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    CurrencyPrecision = group.Add(new VocabularyKey(nameof(CurrencyPrecision), "Currency Precision", VocabularyKeyDataType.Integer, VocabularyKeyVisibility.Visible)); 
			    EntityImageId = group.Add(new VocabularyKey(nameof(EntityImageId), "Entity Image Id", VocabularyKeyDataType.Guid, VocabularyKeyVisibility.Visible));             
            });
            
            #region Incoming Relationships
            ///Property <see cref="ModifiedBy"/> to Vocab 'User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="CreatedBy"/> to Vocab 'User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="OrganizationId"/> to Vocab 'Organization.cdm.json/Organization' with Property 'OrganizationId'
            ///Property <see cref="CreatedOnBehalfBy"/> to Vocab 'User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="ModifiedOnBehalfBy"/> to Vocab 'User.cdm.json/User' with Property 'SystemUserId'
            #endregion
            
            #region Outgoing Relationships
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Activity.cdm.json/Activity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Address.cdm.json/Address' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Appointment.cdm.json/Appointment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Article.cdm.json/Article' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'BusinessUnit.cdm.json/BusinessUnit' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Connection.cdm.json/Connection' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Email.cdm.json/Email' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Fax.cdm.json/Fax' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Feedback.cdm.json/Feedback' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'KnowledgeArticle.cdm.json/KnowledgeArticle' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'KnowledgeArticleViews.cdm.json/KnowledgeArticleViews' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'KnowledgeBaseRecord.cdm.json/KnowledgeBaseRecord' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Letter.cdm.json/Letter' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Organization.cdm.json/Organization' with Property 'BaseCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'PhoneCall.cdm.json/PhoneCall' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Position.cdm.json/Position' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Queue.cdm.json/Queue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'QueueItem.cdm.json/QueueItem' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'RecurringAppointment.cdm.json/RecurringAppointment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'SLA.cdm.json/SLA' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'SLAItem.cdm.json/SLAItem' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'SLAKPIInstance.cdm.json/SLAKPIInstance' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'SocialActivity.cdm.json/SocialActivity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'SocialProfile.cdm.json/SocialProfile' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Task.cdm.json/Task' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Team.cdm.json/Team' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'Territory.cdm.json/Territory' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'User.cdm.json/User' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResource.cdm.json/BookableResource' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResourceBooking.cdm.json/BookableResourceBooking' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResourceBookingHeader.cdm.json/BookableResourceBookingHeader' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResourceCategory.cdm.json/BookableResourceCategory' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResourceCategoryAssn.cdm.json/BookableResourceCategoryAssn' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResourceCharacteristic.cdm.json/BookableResourceCharacteristic' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookableResourceGroup.cdm.json/BookableResourceGroup' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/BookingStatus.cdm.json/BookingStatus' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/Characteristic.cdm.json/Characteristic' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/KnowledgeArticle.cdm.json/KnowledgeArticle' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/Organization.cdm.json/Organization' with Property 'BaseCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/PriceList.cdm.json/PriceList' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/PriceListItem.cdm.json/PriceListItem' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/Product.cdm.json/Product' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/ProductAssociation.cdm.json/ProductAssociation' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/ProductRelationship.cdm.json/ProductRelationship' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/PropertyAssociation.cdm.json/PropertyAssociation' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/PropertyInstance.cdm.json/PropertyInstance' with Property 'DynamicPropertyInstanceid'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/PropertyOptionSetItem.cdm.json/PropertyOptionSetItem' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/RatingModel.cdm.json/RatingModel' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/RatingValue.cdm.json/RatingValue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Activity.cdm.json/Activity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Appointment.cdm.json/Appointment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Campaign.cdm.json/Campaign' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/CampaignActivity.cdm.json/CampaignActivity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/CampaignResponse.cdm.json/CampaignResponse' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Email.cdm.json/Email' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Fax.cdm.json/Fax' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Lead.cdm.json/Lead' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/LeadAddress.cdm.json/LeadAddress' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/Letter.cdm.json/Letter' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/MarketingList.cdm.json/MarketingList' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/PhoneCall.cdm.json/PhoneCall' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/QuickCampaign.cdm.json/QuickCampaign' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/RecurringAppointment.cdm.json/RecurringAppointment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/SocialActivity.cdm.json/SocialActivity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/Lead.cdm.json/Lead' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/ConfigurationOption.cdm.json/ConfigurationOption' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/Deal.cdm.json/Deal' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/DealDevice.cdm.json/DealDevice' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/DealDeviceAddOn.cdm.json/DealDeviceAddOn' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/Device.cdm.json/Device' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/FinancingOpportunity.cdm.json/FinancingOpportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/FinancingOpportunityDetail.cdm.json/FinancingOpportunityDetail' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/LeadDevice.cdm.json/LeadDevice' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/SalesContract.cdm.json/SalesContract' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/SalesContractDetail.cdm.json/SalesContractDetail' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/SalesContractPayment.cdm.json/SalesContractPayment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/ServiceContract.cdm.json/ServiceContract' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/ServiceContractDetail.cdm.json/ServiceContractDetail' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/ServiceOrderJobDetail.cdm.json/ServiceOrderJobDetail' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/SpecificationAccessory.cdm.json/SpecificationAccessory' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/automotive/TradeIn.cdm.json/TradeIn' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/education/higherEducation/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/education/higherEducation/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/education/higherEducation/Address.cdm.json/Address' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/education/higherEducation/Grant.cdm.json/Grant' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/education/higherEducation/Scholarship.cdm.json/Scholarship' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Lead.cdm.json/Lead' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Collateral.cdm.json/Collateral' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/FinancialProduct.cdm.json/FinancialProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Limit.cdm.json/Limit' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/RequestedFacility.cdm.json/RequestedFacility' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Syndicates.cdm.json/Syndicates' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Opportunity.cdm.json/Opportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/financialServices/banking/Product.cdm.json/Product' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Address.cdm.json/Address' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Goal.cdm.json/Goal' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Task.cdm.json/Task' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Address.cdm.json/Address' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Budget.cdm.json/Budget' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/DesignatedCredit.cdm.json/DesignatedCredit' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Designation.cdm.json/Designation' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/DesignationPlan.cdm.json/DesignationPlan' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Disbursement.cdm.json/Disbursement' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/DisbursementDistribution.cdm.json/DisbursementDistribution' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/DonorCommitment.cdm.json/DonorCommitment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/IndicatorValue.cdm.json/IndicatorValue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/PaymentAsset.cdm.json/PaymentAsset' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/PaymentSchedule.cdm.json/PaymentSchedule' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/PlannedGiving.cdm.json/PlannedGiving' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Request.cdm.json/Request' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitCore/Transaction.cdm.json/Transaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/Campaign.cdm.json/Campaign' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/Lead.cdm.json/Lead' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/DesignationPlan.cdm.json/DesignationPlan' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/DonorCommitment.cdm.json/DonorCommitment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/PlannedGiving.cdm.json/PlannedGiving' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/Request.cdm.json/Request' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/Transaction.cdm.json/Transaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitForSales/Opportunity.cdm.json/Opportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Account.cdm.json/Account' with Property 'DefaultCurrency'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Campaign.cdm.json/Campaign' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Expenditure.cdm.json/Expenditure' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/FssForecast.cdm.json/FssForecast' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Budget.cdm.json/Budget' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/DeliveryFramework.cdm.json/DeliveryFramework' with Property 'DefaultCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/DeliveryFramework.cdm.json/DeliveryFramework' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Designation.cdm.json/Designation' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/DesignationPlan.cdm.json/DesignationPlan' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Disbursement.cdm.json/Disbursement' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/DisbursementDistribution.cdm.json/DisbursementDistribution' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/DonorCommitment.cdm.json/DonorCommitment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/IndicatorValue.cdm.json/IndicatorValue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/PaymentSchedule.cdm.json/PaymentSchedule' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/PlannedGiving.cdm.json/PlannedGiving' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Request.cdm.json/Request' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Transaction.cdm.json/Transaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitIati/Opportunity.cdm.json/Opportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitVolunteers/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitVolunteers/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/accelerators/nonProfit/nonProfitVolunteers/Project.cdm.json/Project' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/BookableResource.cdm.json/BookableResource' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/BookableResourceBooking.cdm.json/BookableResourceBooking' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/BookableResourceBookingHeader.cdm.json/BookableResourceBookingHeader' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/BookingStatus.cdm.json/BookingStatus' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/Lead.cdm.json/Lead' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/RatingValue.cdm.json/RatingValue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/User.cdm.json/User' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/BookableResourceCategory.cdm.json/BookableResourceCategory' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/BookableResourceCategoryAssn.cdm.json/BookableResourceCategoryAssn' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/BookableResourceCharacteristic.cdm.json/BookableResourceCharacteristic' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Characteristic.cdm.json/Characteristic' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/ContractLineScheduleOfValue.cdm.json/ContractLineScheduleOfValue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/EstimateLine.cdm.json/EstimateLine' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Expense.cdm.json/Expense' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Fact.cdm.json/Fact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Invoice.cdm.json/Invoice' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/InvoiceLineTransaction.cdm.json/InvoiceLineTransaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/InvoiceProduct.cdm.json/InvoiceProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/JournalLine.cdm.json/JournalLine' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Opportunity.cdm.json/Opportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/OpportunityLineTransaction.cdm.json/OpportunityLineTransaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/OpportunityProduct.cdm.json/OpportunityProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Order.cdm.json/Order' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/OrderLineTransaction.cdm.json/OrderLineTransaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/OrderProduct.cdm.json/OrderProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/PriceList.cdm.json/PriceList' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Product.cdm.json/Product' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Project.cdm.json/Project' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/ProjectApproval.cdm.json/ProjectApproval' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/ProjectServiceApproval.cdm.json/ProjectServiceApproval' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/ProjectTask.cdm.json/ProjectTask' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/Quote.cdm.json/Quote' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/QuoteLineAnalyticsBreakdown.cdm.json/QuoteLineAnalyticsBreakdown' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/QuoteLineScheduleOfValue.cdm.json/QuoteLineScheduleOfValue' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/QuoteLineTransaction.cdm.json/QuoteLineTransaction' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/QuoteProduct.cdm.json/QuoteProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/RatingModel.cdm.json/RatingModel' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/ResourceAssignment.cdm.json/ResourceAssignment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/ResourceCategoryPriceLevel.cdm.json/ResourceCategoryPriceLevel' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/projectServiceAutomation/TransactionCategoryPriceLevel.cdm.json/TransactionCategoryPriceLevel' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/scheduling/Actual.cdm.json/Actual' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/scheduling/BookingAlert.cdm.json/BookingAlert' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/scheduling/Organization.cdm.json/Organization' with Property 'BaseCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/scheduling/OrganizationalUnit.cdm.json/OrganizationalUnit' with Property 'Currency'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/projectCommon/scheduling/ResourceRequirement.cdm.json/ResourceRequirement' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/Competitor.cdm.json/Competitor' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/Discount.cdm.json/Discount' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/DiscountList.cdm.json/DiscountList' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/Invoice.cdm.json/Invoice' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/InvoiceProduct.cdm.json/InvoiceProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/Opportunity.cdm.json/Opportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/OpportunityClose.cdm.json/OpportunityClose' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/OpportunityProduct.cdm.json/OpportunityProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/Order.cdm.json/Order' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/OrderClose.cdm.json/OrderClose' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/OrderProduct.cdm.json/OrderProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/PriceListItem.cdm.json/PriceListItem' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/PropertyInstance.cdm.json/PropertyInstance' with Property 'DynamicPropertyInstanceid'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/Quote.cdm.json/Quote' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/QuoteClose.cdm.json/QuoteClose' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/QuoteProduct.cdm.json/QuoteProduct' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/sales/SalesLiterature.cdm.json/SalesLiterature' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/Case.cdm.json/Case' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/CaseResolution.cdm.json/CaseResolution' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/Contract.cdm.json/Contract' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/ContractLine.cdm.json/ContractLine' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/Entitlement.cdm.json/Entitlement' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/FacilityEquipment.cdm.json/FacilityEquipment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/KnowledgeArticleIncident.cdm.json/KnowledgeArticleIncident' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/ServiceActivity.cdm.json/ServiceActivity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/SLAKPIInstance.cdm.json/SLAKPIInstance' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/Task.cdm.json/Task' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/service/User.cdm.json/User' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/Appointment.cdm.json/Appointment' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/Connection.cdm.json/Connection' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/Lead.cdm.json/Lead' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/MarketingList.cdm.json/MarketingList' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/PhoneCall.cdm.json/PhoneCall' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/Task.cdm.json/Task' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/eventManagement/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/eventManagement/AttendeePass.cdm.json/AttendeePass' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/eventManagement/Building.cdm.json/Building' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/eventManagement/HotelRoomAllocation.cdm.json/HotelRoomAllocation' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/eventManagement/Pass.cdm.json/Pass' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/marketing/eventManagement/SpeakerEngagement.cdm.json/SpeakerEngagement' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/Account.cdm.json/Account' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/Article.cdm.json/Article' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/Case.cdm.json/Case' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/Contact.cdm.json/Contact' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/Feedback.cdm.json/Feedback' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/InviteRedemption.cdm.json/InviteRedemption' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/KnowledgeArticleViews.cdm.json/KnowledgeArticleViews' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/portals/Opportunity.cdm.json/Opportunity' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/crmCommon/solutions/customerInsights/CustomerProfile.cdm.json/CustomerProfile' with Property 'TransactionCurrencyId'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/financialCommon/FinancialActivity.cdm.json/FinancialActivity' with Property 'TransactionCurrencyKey'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/financialCommon/Ledger.cdm.json/Ledger' with Property 'AccountingCurrencyKey'
            ///Property <see cref="TransactionCurrencyId"/> from Vocab 'foundationCommon/financialCommon/MainAccount.cdm.json/MainAccount' with Property 'CurrencyKey'
            #endregion
        }

        public VocabularyKey StatusCode { get; private set; }
        public VocabularyKey ModifiedOn { get; private set; }
        public VocabularyKey StateCode { get; private set; }
        public VocabularyKey VersionNumber { get; private set; }
        public VocabularyKey ImportSequenceNumber { get; private set; }
        public VocabularyKey OverriddenCreatedOn { get; private set; }
        public VocabularyKey CreatedOn { get; private set; }
        public VocabularyKey TransactionCurrencyId { get; private set; }
        public VocabularyKey ExchangeRate { get; private set; }
        public VocabularyKey CurrencySymbol { get; private set; }
        public VocabularyKey CurrencyName { get; private set; }
        public VocabularyKey ISOCurrencyCode { get; private set; }
        public VocabularyKey CurrencyPrecision { get; private set; }
        public VocabularyKey EntityImageId { get; private set; }
    }
}