using CluedIn.Core.Data;
using CluedIn.Core.Data.Vocabularies;

namespace CluedIn.Crawling.CommonDataModel.Vocabularies
{
    public class MarkupDocumentChargeEntityVocabulary : SimpleVocabulary
    {
        public MarkupDocumentChargeEntityVocabulary()
        {
            VocabularyName = "Common Data Model MarkupDocumentChargeEntity";
            KeyPrefix = "commonDataModel.markupdocumentchargeentity";
            KeySeparator = ".";
            Grouping = "/MarkupDocumentChargeEntity";

            AddGroup("Common Data Model MarkupDocumentChargeEntity Details", group =>
            {
                AccountingDate = group.Add(new VocabularyKey(nameof(AccountingDate), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
CalculatedDocumentCurrencyAmount = group.Add(new VocabularyKey(nameof(CalculatedDocumentCurrencyAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeAccountingCurrencyCode = group.Add(new VocabularyKey(nameof(ChargeAccountingCurrencyCode), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeCategory = group.Add(new VocabularyKey(nameof(ChargeCategory), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeCode = group.Add(new VocabularyKey(nameof(ChargeCode), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeCreationMethod = group.Add(new VocabularyKey(nameof(ChargeCreationMethod), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeDescription = group.Add(new VocabularyKey(nameof(ChargeDescription), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeLineNumber = group.Add(new VocabularyKey(nameof(ChargeLineNumber), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeOverrideInformationSubcodeId = group.Add(new VocabularyKey(nameof(ChargeOverrideInformationSubcodeId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
CorrectedDocumentChargeRecId = group.Add(new VocabularyKey(nameof(CorrectedDocumentChargeRecId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
DocumentCurrencyAmount = group.Add(new VocabularyKey(nameof(DocumentCurrencyAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
DocumentStatus = group.Add(new VocabularyKey(nameof(DocumentStatus), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
FromTotalLineAmount = group.Add(new VocabularyKey(nameof(FromTotalLineAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
InfocodeNumber = group.Add(new VocabularyKey(nameof(InfocodeNumber), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsAutomaticCharge = group.Add(new VocabularyKey(nameof(IsAutomaticCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsBrokerContractCharge = group.Add(new VocabularyKey(nameof(IsBrokerContractCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsChargeDeleted = group.Add(new VocabularyKey(nameof(IsChargeDeleted), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsChargeModified = group.Add(new VocabularyKey(nameof(IsChargeModified), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsChargeOverridden = group.Add(new VocabularyKey(nameof(IsChargeOverridden), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsCouponCharge = group.Add(new VocabularyKey(nameof(IsCouponCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsIntercompanyCharge = group.Add(new VocabularyKey(nameof(IsIntercompanyCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsInstallmentPlanCharge = group.Add(new VocabularyKey(nameof(IsInstallmentPlanCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsSalesTaxAutogenerated = group.Add(new VocabularyKey(nameof(IsSalesTaxAutogenerated), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IsTieredCharge = group.Add(new VocabularyKey(nameof(IsTieredCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ModuleCategory = group.Add(new VocabularyKey(nameof(ModuleCategory), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ModuleType = group.Add(new VocabularyKey(nameof(ModuleType), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
OriginalChargeAmount = group.Add(new VocabularyKey(nameof(OriginalChargeAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
SalesTaxDocumentCurrencyAmount = group.Add(new VocabularyKey(nameof(SalesTaxDocumentCurrencyAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
SalesTaxGroupCode = group.Add(new VocabularyKey(nameof(SalesTaxGroupCode), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
SalesTaxItemGroupCode = group.Add(new VocabularyKey(nameof(SalesTaxItemGroupCode), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
SalesTaxPrintCode = group.Add(new VocabularyKey(nameof(SalesTaxPrintCode), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ToTotalLineAmount = group.Add(new VocabularyKey(nameof(ToTotalLineAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
Voucher = group.Add(new VocabularyKey(nameof(Voucher), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
WillInvoiceProcessingKeepCharge = group.Add(new VocabularyKey(nameof(WillInvoiceProcessingKeepCharge), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
Value = group.Add(new VocabularyKey(nameof(Value), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
MCRSavedRecID = group.Add(new VocabularyKey(nameof(MCRSavedRecID), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
MCRSavedTableID = group.Add(new VocabularyKey(nameof(MCRSavedTableID), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeRecId = group.Add(new VocabularyKey(nameof(ChargeRecId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeTableId = group.Add(new VocabularyKey(nameof(ChargeTableId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
SourceDocumentLineRecId = group.Add(new VocabularyKey(nameof(SourceDocumentLineRecId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
DocumentRecId = group.Add(new VocabularyKey(nameof(DocumentRecId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
DocumentTableId = group.Add(new VocabularyKey(nameof(DocumentTableId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
CustInvoiceLineRefId = group.Add(new VocabularyKey(nameof(CustInvoiceLineRefId), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
CustInvoiceLineTemplate = group.Add(new VocabularyKey(nameof(CustInvoiceLineTemplate), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargePercentage = group.Add(new VocabularyKey(nameof(ChargePercentage), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
FixedChargeAmount = group.Add(new VocabularyKey(nameof(FixedChargeAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
IntercompanyChargePercentage = group.Add(new VocabularyKey(nameof(IntercompanyChargePercentage), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
UnitChargeAmount = group.Add(new VocabularyKey(nameof(UnitChargeAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ExternalChargeAmount = group.Add(new VocabularyKey(nameof(ExternalChargeAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ProportionalChargeAmount = group.Add(new VocabularyKey(nameof(ProportionalChargeAmount), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
ChargeClassification = group.Add(new VocabularyKey(nameof(ChargeClassification), VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
             
            });
        }

       public VocabularyKey AccountingDate { get; private set; }
public VocabularyKey CalculatedDocumentCurrencyAmount { get; private set; }
public VocabularyKey ChargeAccountingCurrencyCode { get; private set; }
public VocabularyKey ChargeCategory { get; private set; }
public VocabularyKey ChargeCode { get; private set; }
public VocabularyKey ChargeCreationMethod { get; private set; }
public VocabularyKey ChargeDescription { get; private set; }
public VocabularyKey ChargeLineNumber { get; private set; }
public VocabularyKey ChargeOverrideInformationSubcodeId { get; private set; }
public VocabularyKey CorrectedDocumentChargeRecId { get; private set; }
public VocabularyKey DocumentCurrencyAmount { get; private set; }
public VocabularyKey DocumentStatus { get; private set; }
public VocabularyKey FromTotalLineAmount { get; private set; }
public VocabularyKey InfocodeNumber { get; private set; }
public VocabularyKey IsAutomaticCharge { get; private set; }
public VocabularyKey IsBrokerContractCharge { get; private set; }
public VocabularyKey IsChargeDeleted { get; private set; }
public VocabularyKey IsChargeModified { get; private set; }
public VocabularyKey IsChargeOverridden { get; private set; }
public VocabularyKey IsCouponCharge { get; private set; }
public VocabularyKey IsIntercompanyCharge { get; private set; }
public VocabularyKey IsInstallmentPlanCharge { get; private set; }
public VocabularyKey IsSalesTaxAutogenerated { get; private set; }
public VocabularyKey IsTieredCharge { get; private set; }
public VocabularyKey ModuleCategory { get; private set; }
public VocabularyKey ModuleType { get; private set; }
public VocabularyKey OriginalChargeAmount { get; private set; }
public VocabularyKey SalesTaxDocumentCurrencyAmount { get; private set; }
public VocabularyKey SalesTaxGroupCode { get; private set; }
public VocabularyKey SalesTaxItemGroupCode { get; private set; }
public VocabularyKey SalesTaxPrintCode { get; private set; }
public VocabularyKey ToTotalLineAmount { get; private set; }
public VocabularyKey Voucher { get; private set; }
public VocabularyKey WillInvoiceProcessingKeepCharge { get; private set; }
public VocabularyKey Value { get; private set; }
public VocabularyKey MCRSavedRecID { get; private set; }
public VocabularyKey MCRSavedTableID { get; private set; }
public VocabularyKey ChargeRecId { get; private set; }
public VocabularyKey ChargeTableId { get; private set; }
public VocabularyKey SourceDocumentLineRecId { get; private set; }
public VocabularyKey DocumentRecId { get; private set; }
public VocabularyKey DocumentTableId { get; private set; }
public VocabularyKey CustInvoiceLineRefId { get; private set; }
public VocabularyKey CustInvoiceLineTemplate { get; private set; }
public VocabularyKey ChargePercentage { get; private set; }
public VocabularyKey FixedChargeAmount { get; private set; }
public VocabularyKey IntercompanyChargePercentage { get; private set; }
public VocabularyKey UnitChargeAmount { get; private set; }
public VocabularyKey ExternalChargeAmount { get; private set; }
public VocabularyKey ProportionalChargeAmount { get; private set; }
public VocabularyKey ChargeClassification { get; private set; }


    }
}