using CluedIn.Core.Data;
using CluedIn.Core.Data.Vocabularies;

namespace CluedIn.Vocabularies.CommonDataModel.ElectronicMedicalRecords
{
    public class CodeableConceptVocabulary : SimpleVocabulary
    {
        public CodeableConceptVocabulary()
        {
            VocabularyName = "Codeable Concept";
            KeyPrefix = "commonDataModel.codeableconcept.electronicmedicalrecords";
            KeySeparator = ".";
            Grouping = CommonDataModelEntityTypes.CodeableConcept;

            AddGroup("CodeableConcept Details for ElectronicMedicalRecords", group =>
            {
			    CreatedOn = group.Add(new VocabularyKey(nameof(CreatedOn), "Created On", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    CreatedOnBehalfBy = group.Add(new VocabularyKey(nameof(CreatedOnBehalfBy), "Created By (Delegate)", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    EntityImage = group.Add(new VocabularyKey(nameof(EntityImage), "Entity Image", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    ImportSequenceNumber = group.Add(new VocabularyKey(nameof(ImportSequenceNumber), "Import Sequence Number", VocabularyKeyDataType.Integer, VocabularyKeyVisibility.Visible)); 
			    ModifiedOn = group.Add(new VocabularyKey(nameof(ModifiedOn), "Modified On", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    ModifiedOnBehalfBy = group.Add(new VocabularyKey(nameof(ModifiedOnBehalfBy), "Modified By (Delegate)", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    Code = group.Add(new VocabularyKey(nameof(Code), "Code", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    CodeableConceptId = group.Add(new VocabularyKey(nameof(CodeableConceptId), "Codeable Concept", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    Name = group.Add(new VocabularyKey(nameof(Name), "Name", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    Text = group.Add(new VocabularyKey(nameof(Text), "Text", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    Type = group.Add(new VocabularyKey(nameof(Type), "Type", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    OverriddenCreatedOn = group.Add(new VocabularyKey(nameof(OverriddenCreatedOn), "Record Created On", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    StateCode = group.Add(new VocabularyKey(nameof(StateCode), "Status", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    StatusCode = group.Add(new VocabularyKey(nameof(StatusCode), "Status Reason", VocabularyKeyDataType.Text, VocabularyKeyVisibility.Visible)); 
			    TimeZoneRuleVersionNumber = group.Add(new VocabularyKey(nameof(TimeZoneRuleVersionNumber), "Time Zone Rule Version Number", VocabularyKeyDataType.Integer, VocabularyKeyVisibility.Visible)); 
			    UTCConversionTimeZoneCode = group.Add(new VocabularyKey(nameof(UTCConversionTimeZoneCode), "UTC Conversion Time Zone Code", VocabularyKeyDataType.Integer, VocabularyKeyVisibility.Visible));             
            });
            
            #region Incoming Relationships
            ///Property <see cref="CreatedBy"/> to Vocab '/core/applicationCommon/User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="ModifiedBy"/> to Vocab '/core/applicationCommon/User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="OrganizationId"/> to Vocab '/core/applicationCommon/Organization.cdm.json/Organization' with Property 'OrganizationId'
            ///Property <see cref="CodeFilterValueCodeableConceptId"/> to Vocab 'CodeableConcept.cdm.json/CodeableConcept' with Property 'CodeableConceptId'
            ///Property <see cref="DataRequirementCodeFilterId"/> to Vocab 'DataRequirementCodeFilter.cdm.json/DataRequirementCodeFilter' with Property 'DataRequirementCodeFilterId'
            ///Property <see cref="CreatedBy"/> to Vocab '/core/applicationCommon/User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="ModifiedBy"/> to Vocab '/core/applicationCommon/User.cdm.json/User' with Property 'SystemUserId'
            ///Property <see cref="OrganizationId"/> to Vocab '/core/applicationCommon/Organization.cdm.json/Organization' with Property 'OrganizationId'
            #endregion
            
            #region Outgoing Relationships
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Account.cdm.json/Account' with Property 'Contact1PuroposeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Account.cdm.json/Account' with Property 'Contact2PuroposeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'AnimalBreedId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'AnimalGenderStatusId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'AnimalSpeciesId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'Communication1LanguageId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'Communication2LanguageId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'Contact1RelationshipId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'Contact2RelationshipId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'Link1TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Contact.cdm.json/Contact' with Property 'Link2TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionBodySite.cdm.json/ActivityDefinitionBodySite' with Property 'BodySiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionJurisdiction.cdm.json/ActivityDefinitionJurisdiction' with Property 'JurisdictionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionLibrary.cdm.json/ActivityDefinitionLibrary' with Property 'LibraryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionParticipant.cdm.json/ActivityDefinitionParticipant' with Property 'RoleId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionTopic.cdm.json/ActivityDefinitionTopic' with Property 'TopicId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionUseContext.cdm.json/ActivityDefinitionUseContext' with Property 'QuantityCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinitionUseContext.cdm.json/ActivityDefinitionUseContext' with Property 'ValuecodeableconceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMR.cdm.json/AppointmentEMR' with Property 'AppointmentTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMR.cdm.json/AppointmentEMR' with Property 'ParticpantTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMR.cdm.json/AppointmentEMR' with Property 'ServiceCategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMRParticipant.cdm.json/AppointmentEMRParticipant' with Property 'ParticpantTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMRReason.cdm.json/AppointmentEMRReason' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMRServiceType.cdm.json/AppointmentEMRServiceType' with Property 'ServiceTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentEMRSpecialty.cdm.json/AppointmentEMRSpecialty' with Property 'SpecialtyCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'AppointmentServiceCategory.cdm.json/AppointmentServiceCategory' with Property 'ServiceCategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlan.cdm.json/CarePlan' with Property 'GroupIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanActivity.cdm.json/CarePlanActivity' with Property 'ActivityCategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanActivity.cdm.json/CarePlanActivity' with Property 'ActivityCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanActivity.cdm.json/CarePlanActivity' with Property 'ActivityDefinitionTypeQuestionnaireId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanActivity.cdm.json/CarePlanActivity' with Property 'ActivityProductCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanActivityOutcome.cdm.json/CarePlanActivityOutcome' with Property 'ActivityOutcomeIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanActivityReason.cdm.json/CarePlanActivityReason' with Property 'PlanActivityReasonCodeIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanCategory.cdm.json/CarePlanCategory' with Property 'PlanCategoryIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CarePlanDefinition.cdm.json/CarePlanDefinition' with Property 'DefinitionTypePQuestionnaireId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CareTeam.cdm.json/CareTeam' with Property 'SubjectGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CareTeamCategory.cdm.json/CareTeamCategory' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CareTeamParticipant.cdm.json/CareTeamParticipant' with Property 'RoleId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CareTeamReasonCode.cdm.json/CareTeamReasonCode' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpression.cdm.json/ClinicalImpression' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpression.cdm.json/ClinicalImpression' with Property 'SubjectGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigation.cdm.json/ClinicalImpressionInvestigation' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigation.cdm.json/ClinicalImpressionInvestigation' with Property 'ItemDiagnosticReportId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigation.cdm.json/ClinicalImpressionInvestigation' with Property 'ItemImagingStudyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigation.cdm.json/ClinicalImpressionInvestigation' with Property 'ItemQuestionaireResponseId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigationItem.cdm.json/ClinicalImpressionInvestigationItem' with Property 'ItemtypeDiagnosticReportId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigationItem.cdm.json/ClinicalImpressionInvestigationItem' with Property 'ItemTypeImagingStudyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionInvestigationItem.cdm.json/ClinicalImpressionInvestigationItem' with Property 'ItemtypeQuestionnaireResponseId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ClinicalImpressionPrognosis.cdm.json/ClinicalImpressionPrognosis' with Property 'ConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Communication.cdm.json/Communication' with Property 'CommunicationLanguageId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CommunicationRequest.cdm.json/CommunicationRequest' with Property 'PriorityId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CommunicationRequest.cdm.json/CommunicationRequest' with Property 'SubjectGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CommunicationRequestCategory.cdm.json/CommunicationRequestCategory' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CommunicationRequestMedium.cdm.json/CommunicationRequestMedium' with Property 'MediumId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CommunicationRequestReason.cdm.json/CommunicationRequestReason' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'CommunicationRequestRecipient.cdm.json/CommunicationRequestRecipient' with Property 'RecipientGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Condition.cdm.json/Condition' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Condition.cdm.json/Condition' with Property 'ConditionCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Condition.cdm.json/Condition' with Property 'SeverityId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Condition.cdm.json/Condition' with Property 'StageId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Condition.cdm.json/Condition' with Property 'SubjectTypeGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ConditionBodySite.cdm.json/ConditionBodySite' with Property 'BodySiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ConditionCategory.cdm.json/ConditionCategory' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ConditionEvidence.cdm.json/ConditionEvidence' with Property 'EvidenceCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ConditionStage.cdm.json/ConditionStage' with Property 'StageAssessmentDiagnosticRecordId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ContactLink.cdm.json/ContactLink' with Property 'LinkTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DataRequirement.cdm.json/DataRequirement' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DataRequirementCodeFilter.cdm.json/DataRequirementCodeFilter' with Property 'CodeFilterValueSetReferenceId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DataRequirementCodeFilterValueCode.cdm.json/DataRequirementCodeFilterValueCode' with Property 'CodeFilterValueCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DataReqCodeFilterValueCodeableConcept.cdm.json/DataReqCodeFilterValueCodeableConcept' with Property 'CodeFilterValueCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DataRequirementCodeFilterValueCoding.cdm.json/DataRequirementCodeFilterValueCoding' with Property 'CodeFilterValueCodingId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Device.cdm.json/Device' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceComponent.cdm.json/DeviceComponent' with Property 'LanguageCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceComponent.cdm.json/DeviceComponent' with Property 'ParameterGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceComponent.cdm.json/DeviceComponent' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceComponentOperationalStatus.cdm.json/DeviceComponentOperationalStatus' with Property 'OperationalStatusId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceComponentProductionSpecification.cdm.json/DeviceComponentProductionSpecification' with Property 'SpecTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceMetric.cdm.json/DeviceMetric' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceMetric.cdm.json/DeviceMetric' with Property 'UnitNewId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceRequest.cdm.json/DeviceRequest' with Property 'CodeTypeCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceRequest.cdm.json/DeviceRequest' with Property 'DeviceRequestPerformerTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceRequest.cdm.json/DeviceRequest' with Property 'IntentId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceRequest.cdm.json/DeviceRequest' with Property 'SubjectTypeGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceRequestReasonCode.cdm.json/DeviceRequestReasonCode' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DeviceRequestRelevantHistory.cdm.json/DeviceRequestRelevantHistory' with Property 'RelevantHistoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'AsNeededTypeCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'MaxDosePeriodRatioQuantityDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'MaxDosePeriodRatioQuantityNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'MethodId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'RateRatioQuantityDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'RateRatioQuantityNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'RouteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Dosage.cdm.json/Dosage' with Property 'SiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'DosageAddInstruction.cdm.json/DosageAddInstruction' with Property 'DosageAdditionalInstructionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Encounter.cdm.json/Encounter' with Property 'EncounterGroupIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Encounter.cdm.json/Encounter' with Property 'EncounterPriorityId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Encounter.cdm.json/Encounter' with Property 'HospitalizationAdmitSourceId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Encounter.cdm.json/Encounter' with Property 'HospitalizationDischargeDispositionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Encounter.cdm.json/Encounter' with Property 'HospitalizationReadmissionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EncounterDiagnosis.cdm.json/EncounterDiagnosis' with Property 'EncounterRoleId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EncounterHospitalizationArrangement.cdm.json/EncounterHospitalizationArrangement' with Property 'SpecialArrangementIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EncounterHospitalizationCourtesy.cdm.json/EncounterHospitalizationCourtesy' with Property 'SpecialCourtesyIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EncounterHospitalizationDiet.cdm.json/EncounterHospitalizationDiet' with Property 'EncounterDietPreferenceId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EncounterReason.cdm.json/EncounterReason' with Property 'EncounterReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Endpoint.cdm.json/Endpoint' with Property 'PayloadTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EndpointPayloadType.cdm.json/EndpointPayloadType' with Property 'PayloadTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EpisodeOfCareAccount.cdm.json/EpisodeOfCareAccount' with Property 'AccountId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EpisodeOfCareDiagnosis.cdm.json/EpisodeOfCareDiagnosis' with Property 'ConditionRoleId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'EpisodeOfCareType.cdm.json/EpisodeOfCareType' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistory.cdm.json/FamilyMemberHistory' with Property 'NotDoneReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistory.cdm.json/FamilyMemberHistory' with Property 'RelationshipId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistoryCondition.cdm.json/FamilyMemberHistoryCondition' with Property 'ConditionCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistoryCondition.cdm.json/FamilyMemberHistoryCondition' with Property 'ConditionOutcomeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistoryDefinition.cdm.json/FamilyMemberHistoryDefinition' with Property 'QuestionnaireId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistoryReason.cdm.json/FamilyMemberHistoryReason' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'FamilyMemberHistoryReasonReference.cdm.json/FamilyMemberHistoryReasonReference' with Property 'ReasonReferenceQuestionnaireResponseId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalDescriptionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalPriorityId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalStartCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalSubjectGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalTargetDetailQuantityCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalTargetDetailValueCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Goal.cdm.json/Goal' with Property 'GoalTargetMeasureId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'GoalAddresses.cdm.json/GoalAddresses' with Property 'AddressesTypeMedicationStatementId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'GoalOutcome.cdm.json/GoalOutcome' with Property 'GoalOutcomeCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareService.cdm.json/HealthcareService' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareService.cdm.json/HealthcareService' with Property 'EligibilityId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareServiceCategory.cdm.json/HealthcareServiceCategory' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareServiceCharacteristic.cdm.json/HealthcareServiceCharacteristic' with Property 'CharacteristicsId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareServiceProvision.cdm.json/HealthcareServiceProvision' with Property 'ServiceProvisionCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareServiceReferralMethod.cdm.json/HealthcareServiceReferralMethod' with Property 'ReferralMethodId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'HealthcareServiceSpecialty.cdm.json/HealthcareServiceSpecialty' with Property 'SpecialtyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinition.cdm.json/ActivityDefinition' with Property 'KindId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinition.cdm.json/ActivityDefinition' with Property 'ProductconceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ActivityDefinition.cdm.json/ActivityDefinition' with Property 'TransformId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Location.cdm.json/Location' with Property 'PhysicalTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Location.cdm.json/Location' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Medication.cdm.json/Medication' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Medication.cdm.json/Medication' with Property 'FormId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Medication.cdm.json/Medication' with Property 'MedicationCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Medication.cdm.json/Medication' with Property 'PackageContainerId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'DosageMethodId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'DosageRouteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'DosageSiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'MedicationCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'RateRatioQuantityNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'RatioDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministration.cdm.json/MedicationAdministration' with Property 'SubjectTypeGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministrationEventHistory.cdm.json/MedicationAdministrationEventHistory' with Property 'EventHistoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministrationReasonCode.cdm.json/MedicationAdministrationReasonCode' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationAdministrationReasonNotGiven.cdm.json/MedicationAdministrationReasonNotGiven' with Property 'ReasonNotGivenId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationIngredient.cdm.json/MedicationIngredient' with Property 'IngredientItemCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationPackageContent.cdm.json/MedicationPackageContent' with Property 'PackageItemCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationRequest.cdm.json/MedicationRequest' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationRequest.cdm.json/MedicationRequest' with Property 'MedicationTypeCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationRequest.cdm.json/MedicationRequest' with Property 'SubjectTypeGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationRequest.cdm.json/MedicationRequest' with Property 'SubstitutionReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationRequestDetectedIssue.cdm.json/MedicationRequestDetectedIssue' with Property 'MedicationRequestetectedIssueId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'MedicationRequestReasonCode.cdm.json/MedicationRequestReasonCode' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrder.cdm.json/NutritionOrder' with Property 'AdditiveTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrder.cdm.json/NutritionOrder' with Property 'BaseFormulaTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrder.cdm.json/NutritionOrder' with Property 'RouteOfAdministrationId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderAllergyIntolerance.cdm.json/NutritionOrderAllergyIntolerance' with Property 'AllergyIntoleranceId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderEnteralFormulaAdministration.cdm.json/NutritionOrderEnteralFormulaAdministration' with Property 'RateRatioQuantityDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderEnteralFormulaAdministration.cdm.json/NutritionOrderEnteralFormulaAdministration' with Property 'RateRatioQuantityNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderExcludeFoodModifier.cdm.json/NutritionOrderExcludeFoodModifier' with Property 'ExcludeFoodModifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderFoodPreferenceModifier.cdm.json/NutritionOrderFoodPreferenceModifier' with Property 'FoodPreferenceModifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderOralDietFluidConsistencyType.cdm.json/NutritionOrderOralDietFluidConsistencyType' with Property 'OralDietFluidConsistencyTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderOralDietNutrient.cdm.json/NutritionOrderOralDietNutrient' with Property 'OralDietNutrientModifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderOralDietTexture.cdm.json/NutritionOrderOralDietTexture' with Property 'OralDietTextureFoodTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderOralDietTexture.cdm.json/NutritionOrderOralDietTexture' with Property 'OralDietTextureModifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderOralDietType.cdm.json/NutritionOrderOralDietType' with Property 'OralDietTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'NutritionOrderSupplement.cdm.json/NutritionOrderSupplement' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'BodySiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'DataAbsentReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'InterpretationId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'MethodId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'SubjectTypeGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'ValueCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'ValueQuantityCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'ValueRatioDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Observation.cdm.json/Observation' with Property 'ValueRatioNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationBasedOn.cdm.json/ObservationBasedOn' with Property 'ObsBasedOnTypeImmunizationRequestId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ComponentDataAbsentReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ComponentInterpretationId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ObsComponentCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ValueCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ValueQuantityCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ValueRatioDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationComponent.cdm.json/ObservationComponent' with Property 'ValueRatioNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationReferenceRange.cdm.json/ObservationReferenceRange' with Property 'RangeTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationReferenceRangeAppliesTo.cdm.json/ObservationReferenceRangeAppliesTo' with Property 'ObsReferenceRangeAppliesToId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationRelatedResource.cdm.json/ObservationRelatedResource' with Property 'ObsRelatedResourceQuestionaireResponseId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ObservationRelatedResource.cdm.json/ObservationRelatedResource' with Property 'ObsRelatedResourceSequenceIdentfierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionAction.cdm.json/PlanDefinitionAction' with Property 'TransformId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionActionCode.cdm.json/PlanDefinitionActionCode' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionActionReason.cdm.json/PlanDefinitionActionReason' with Property 'ReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionGoal.cdm.json/PlanDefinitionGoal' with Property 'DescriptionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionGoal.cdm.json/PlanDefinitionGoal' with Property 'StartEventId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionGoalAddresses.cdm.json/PlanDefinitionGoalAddresses' with Property 'GoalAddressesId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionGoalTarget.cdm.json/PlanDefinitionGoalTarget' with Property 'GoalMeasureId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionGoalTarget.cdm.json/PlanDefinitionGoalTarget' with Property 'QuantityCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionGoalTarget.cdm.json/PlanDefinitionGoalTarget' with Property 'ValueconceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionJurisdiction.cdm.json/PlanDefinitionJurisdiction' with Property 'JurisdictionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionLibrary.cdm.json/PlanDefinitionLibrary' with Property 'LibraryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionParticipant.cdm.json/PlanDefinitionParticipant' with Property 'RoleId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionTopic.cdm.json/PlanDefinitionTopic' with Property 'TopicId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PlanDefinitionUseContext.cdm.json/PlanDefinitionUseContext' with Property 'ValuecodeableconceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PractitionerQualification.cdm.json/PractitionerQualification' with Property 'QualificationCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PractitionerRoleCode.cdm.json/PractitionerRoleCode' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'PractitionerRoleSpecialty.cdm.json/PractitionerRoleSpecialty' with Property 'SpecialtyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Procedure.cdm.json/Procedure' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Procedure.cdm.json/Procedure' with Property 'CodeableconceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Procedure.cdm.json/Procedure' with Property 'GroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Procedure.cdm.json/Procedure' with Property 'NotDoneReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Procedure.cdm.json/Procedure' with Property 'OutcomeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureBodySite.cdm.json/ProcedureBodySite' with Property 'BodySiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureComplication.cdm.json/ProcedureComplication' with Property 'ComplicationIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureFocalDevice.cdm.json/ProcedureFocalDevice' with Property 'FoculDeviceActionId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureFollowUp.cdm.json/ProcedureFollowUp' with Property 'ComplicationConditionIdentifierId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedurePerformer.cdm.json/ProcedurePerformer' with Property 'PerformerRoleId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureReason.cdm.json/ProcedureReason' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureReport.cdm.json/ProcedureReport' with Property 'ReportId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequest.cdm.json/ProcedureRequest' with Property 'AsNeededCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequest.cdm.json/ProcedureRequest' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequest.cdm.json/ProcedureRequest' with Property 'SubjectGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequestBodySite.cdm.json/ProcedureRequestBodySite' with Property 'BodySiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequestCategory.cdm.json/ProcedureRequestCategory' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequestReasonCode.cdm.json/ProcedureRequestReasonCode' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureRequestRelevantHistory.cdm.json/ProcedureRequestRelevantHistory' with Property 'RelevantHistoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ProcedureUsedCode.cdm.json/ProcedureUsedCode' with Property 'CodedItemId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ReferralRequest.cdm.json/ReferralRequest' with Property 'PractitionerSpecialtyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ReferralRequest.cdm.json/ReferralRequest' with Property 'SubjectGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ReferralRequest.cdm.json/ReferralRequest' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ReferralRequestReasonCode.cdm.json/ReferralRequestReasonCode' with Property 'ReasonCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ReferralRequestRelevantHistory.cdm.json/ReferralRequestRelevantHistory' with Property 'RelevantHistoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ReferralRequestServiceRequested.cdm.json/ReferralRequestServiceRequested' with Property 'ServiceRequestedId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RelatedPerson.cdm.json/RelatedPerson' with Property 'RelationshipId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RequestGroup.cdm.json/RequestGroup' with Property 'ReasonCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RequestGroupActionCode.cdm.json/RequestGroupActionCode' with Property 'ActionCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RiskAssessment.cdm.json/RiskAssessment' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RiskAssessment.cdm.json/RiskAssessment' with Property 'MethodId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RiskAssessment.cdm.json/RiskAssessment' with Property 'ReasonConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RiskAssessment.cdm.json/RiskAssessment' with Property 'SubjectgroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'RiskAssessmentPrediction.cdm.json/RiskAssessmentPrediction' with Property 'OutcomeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Schedule.cdm.json/Schedule' with Property 'ServiceCategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'ScheduleSpecialty.cdm.json/ScheduleSpecialty' with Property 'SpecialtyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Slot.cdm.json/Slot' with Property 'ServiceCategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Slot.cdm.json/Slot' with Property 'SpecialtyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SlotServiceType.cdm.json/SlotServiceType' with Property 'SlotservicetypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SlotSpecialty.cdm.json/SlotSpecialty' with Property 'SpecialtyId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Specimen.cdm.json/Specimen' with Property 'BodySiteId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Specimen.cdm.json/Specimen' with Property 'CollectedMethodId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Specimen.cdm.json/Specimen' with Property 'SubjectTypeGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Specimen.cdm.json/Specimen' with Property 'TypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SpecimenContainer.cdm.json/SpecimenContainer' with Property 'ContainerAdditiveCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SpecimenContainer.cdm.json/SpecimenContainer' with Property 'ContainerTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SpecimenProcessing.cdm.json/SpecimenProcessing' with Property 'ProcessingProcedureId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Substance.cdm.json/Substance' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SubstanceCategory.cdm.json/SubstanceCategory' with Property 'CategoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SubstanceIngredient.cdm.json/SubstanceIngredient' with Property 'IngredientQuantityDenominatorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SubstanceIngredient.cdm.json/SubstanceIngredient' with Property 'IngredientQuantityNumeratorCodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'SubstanceIngredient.cdm.json/SubstanceIngredient' with Property 'IngredientSubstanceCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'TaskInput.cdm.json/TaskInput' with Property 'InputTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'TaskOutput.cdm.json/TaskOutput' with Property 'OutputTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'TaskPerformerType.cdm.json/TaskPerformerType' with Property 'PerformerTypeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'TaskRelevantHistory.cdm.json/TaskRelevantHistory' with Property 'RelevantHistoryId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'TaskRestrictionRecipient.cdm.json/TaskRestrictionRecipient' with Property 'RestrictionRecipientGroupId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'VisionPrescription.cdm.json/VisionPrescription' with Property 'ReasonCodeableConceptId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'VisionPrescriptionDispense.cdm.json/VisionPrescriptionDispense' with Property 'DispenseProductId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Task.cdm.json/Task' with Property 'BusinessStatusId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Task.cdm.json/Task' with Property 'CodeId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Task.cdm.json/Task' with Property 'ReasonId'
            ///Property <see cref="CodeableConceptId"/> from Vocab 'Task.cdm.json/Task' with Property 'StatusReasonId'
            #endregion
        }

        public VocabularyKey CreatedOn { get; private set; }
        public VocabularyKey CreatedOnBehalfBy { get; private set; }
        public VocabularyKey EntityImage { get; private set; }
        public VocabularyKey ImportSequenceNumber { get; private set; }
        public VocabularyKey ModifiedOn { get; private set; }
        public VocabularyKey ModifiedOnBehalfBy { get; private set; }
        public VocabularyKey Code { get; private set; }
        public VocabularyKey CodeableConceptId { get; private set; }
        public VocabularyKey Name { get; private set; }
        public VocabularyKey Text { get; private set; }
        public VocabularyKey Type { get; private set; }
        public VocabularyKey OverriddenCreatedOn { get; private set; }
        public VocabularyKey StateCode { get; private set; }
        public VocabularyKey StatusCode { get; private set; }
        public VocabularyKey TimeZoneRuleVersionNumber { get; private set; }
        public VocabularyKey UTCConversionTimeZoneCode { get; private set; }
    }
}